-- Run this as a whole block in Postgres to create all of the tables you will need

CREATE TABLE allergies (
 START date
,STOP date
,PATIENT varchar(1000)
,ENCOUNTER varchar(1000)
,CODE varchar(1000)
,SYSTEM varchar(1000)
,DESCRIPTION varchar(1000)
,TYPE varchar(1000)
,CATEGORY varchar(1000)
,REACTION1 varchar(1000)
,DESCRIPTION1 varchar(1000)
,SEVERITY1 varchar(1000)
,REACTION2 varchar(1000)
,DESCRIPTION2 varchar(1000)
,SEVERITY2 varchar(1000)
);

CREATE TABLE careplans (
 ID varchar(1000)
,START varchar(1000)
,STOP varchar(1000)
,PATIENT varchar(1000)
,ENCOUNTER varchar(1000)
,CODE varchar(1000)
,DESCRIPTION varchar(1000)
,REASONCODE varchar(1000)
,REASONDESCRIPTION varchar(1000)
);	


CREATE TABLE claims
(
 Id VARCHAR(1000)
,PATIENTID VARCHAR(1000)
,PROVIDERID VARCHAR(1000)
,PRIMARYPATIENTINSURANCEID VARCHAR(1000)
,SECONDARYPATIENTINSURANCEID VARCHAR(1000)
,DEPARTMENTID VARCHAR(1000)
,PATIENTDEPARTMENTID VARCHAR(1000)
,DIAGNOSIS1 VARCHAR(1000)
,DIAGNOSIS2 VARCHAR(1000)
,DIAGNOSIS3 VARCHAR(1000)
,DIAGNOSIS4 VARCHAR(1000)
,DIAGNOSIS5 VARCHAR(1000)
,DIAGNOSIS6 VARCHAR(1000)
,DIAGNOSIS7 VARCHAR(1000)
,DIAGNOSIS8 VARCHAR(1000)
,REFERRINGPROVIDERID VARCHAR(1000)
,APPOINTMENTID VARCHAR(1000)
,CURRENTILLNESSDATE TIMESTAMP
,SERVICEDATE TIMESTAMP
,SUPERVISINGPROVIDERID VARCHAR(1000)
,STATUS1 VARCHAR(1000)
,STATUS2 VARCHAR(1000)
,STATUSP VARCHAR(1000)
,OUTSTANDING1 VARCHAR(1000)
,OUTSTANDING2 VARCHAR(1000)
,OUTSTANDINGP VARCHAR(1000)
,LASTBILLEDDATE1 TIMESTAMP
,LASTBILLEDDATE2 TIMESTAMP
,LASTBILLEDDATEP TIMESTAMP
,HEALTHCARECLAIMTYPEID1 VARCHAR(1000)
,HEALTHCARECLAIMTYPEID2 VARCHAR(1000)
);


CREATE TABLE claims_transactions
(
 ID VARCHAR(1000)
,CLAIMID VARCHAR(1000)
,CHARGEID VARCHAR(1000)
,PATIENTID VARCHAR(1000)
,TYPE VARCHAR(1000)
,AMOUNT FLOAT
,METHOD VARCHAR(1000)
,FROMDATE DATE
,TODATE DATE
,PLACEOFSERVICE VARCHAR(1000)
,PROCEDURECODE VARCHAR(1000)
,MODIFIER1 VARCHAR(1000)
,MODIFIER2 VARCHAR(1000)
,DIAGNOSISREF1 INT
,DIAGNOSISREF2 INT
,DIAGNOSISREF3 INT
,DIAGNOSISREF4 INT
,UNITS INT
,DEPARTMENTID VARCHAR(100)
,NOTES VARCHAR(1000)
,UNITAMOUNT FLOAT
,TRANSFEROUTID VARCHAR(1000)
,TRANSFERTYPE VARCHAR(1000)
,PAYMENTS FLOAT
,ADJUSTMENTS INT
,TRANSFERS FLOAT
,OUTSTANDING FLOAT
,APPOINTMENTID VARCHAR(1000)
,LINENOTE VARCHAR(1000)
,PATIENTINSURANCEID VARCHAR(1000)
,FEESCHEDULEID VARCHAR(1000)
,PROVIDERID VARCHAR(1000)
,SUPERVISINGPROVIDERID VARCHAR(1000)
);


CREATE TABLE conditions (
START DATE
,STOP DATE
,PATIENT VARCHAR(1000)
,ENCOUNTER VARCHAR(1000)
,CODE VARCHAR(1000)
,DESCRIPTION VARCHAR(200)
);


CREATE TABLE devices (
 START TIMESTAMP
,STOP TIMESTAMP
,PATIENT VARCHAR(200)
,ENCOUNTER VARCHAR(200)
,CODE VARCHAR(200)
,DESCRIPTION VARCHAR(200)
,UDI VARCHAR(100)
);


CREATE TABLE encounters (
 Id VARCHAR(100)
,START TIMESTAMP
,STOP TIMESTAMP
,PATIENT VARCHAR(100)
,ORGANIZATION VARCHAR(100)
,PROVIDER VARCHAR(100)
,PAYER VARCHAR(100)
,ENCOUNTERCLASS VARCHAR(100)
,CODE VARCHAR(100)
,DESCRIPTION VARCHAR(100)
,BASE_ENCOUNTER_COST FLOAT
,TOTAL_CLAIM_COST FLOAT
,PAYER_COVERAGE FLOAT
,REASONCODE VARCHAR(100)
,REASONDESCRIPTION VARCHAR(100)
);

CREATE TABLE imaging_studies (
 Id varchar(100)
,DATE DATE
,PATIENT varchar(100)
,ENCOUNTER varchar(100)
,SERIES_UID varchar(100)
,BODYSITE_CODE varchar(100)
,BODYSITE_DESCRIPTION varchar(100)
,MODALITY_CODE varchar(100)
,MODALITY_DESCRIPTION varchar(100)
,INSTANCE_UID varchar(100)
,SOP_CODE varchar(100)
,SOP_DESCRIPTION varchar(100) 
,PROCEDURE_CODE varchar(100)
);

CREATE TABLE immunizations
(
 DATE TIMESTAMP
,PATIENT varchar(100)
,ENCOUNTER varchar(100)
,CODE int
,DESCRIPTION varchar(500)
,BASE_COST float
);

CREATE TABLE medications
(
 START timestamp
,STOP timestamp
,PATIENT VARCHAR(100)
,PAYER VARCHAR(100)
,ENCOUNTER VARCHAR(100)
,CODE VARCHAR(100)
,DESCRIPTION VARCHAR(500)
,BASE_COST float
,PAYER_COVERAGE float
,DISPENSES float
,TOTALCOST float
,REASONCODE VARCHAR(100)
,REASONDESCRIPTION VARCHAR(100)
);

CREATE TABLE observations
(
 DATE timestamp
,PATIENT VARCHAR(100)
,ENCOUNTER VARCHAR(100)
,CATEGORY VARCHAR(100)
,CODE VARCHAR(100)
,DESCRIPTION VARCHAR(500)
,VALUE VARCHAR(500)
,UNITS VARCHAR(100)
,TYPE VARCHAR(100)
);

CREATE TABLE organizations
(
 Id varchar(100)
,NAME varchar(100)
,ADDRESS varchar(100)
,CITY varchar(50)
,STATE varchar(3)
,ZIP int
,LAT float
,LON float
,PHONE varchar(100)
,REVENUE float
,UTILIZATION int
);

CREATE TABLE patients
(
 Id VARCHAR(100)
,BIRTHDATE date
,DEATHDATE date
,SSN VARCHAR(100)
,DRIVERS VARCHAR(100)
,PASSPORT VARCHAR(100)
,PREFIX VARCHAR(100)
,FIRST VARCHAR(100)
,LAST VARCHAR(100)
,SUFFIX VARCHAR(100)
,MAIDEN VARCHAR(100)
,MARITAL VARCHAR(100)
,RACE VARCHAR(100)
,ETHNICITY VARCHAR(100)
,GENDER VARCHAR(100)
,BIRTHPLACE VARCHAR(100)
,ADDRESS VARCHAR(100)
,CITY VARCHAR(100)
,STATE VARCHAR(100)
,COUNTY VARCHAR(100)
,FIPS INT 
,ZIP INT
,LAT float
,LON float
,HEALTHCARE_EXPENSES float
,HEALTHCARE_COVERAGE float
,INCOME int
);

CREATE TABLE payer_transitions
(
 PATIENT VARCHAR(100)
,MEMBERID VARCHAR(100)
,START_DATE timestamp
,END_DATE timestamp
,PAYER VARCHAR(100)
,SECONDARY_PAYER VARCHAR(100)
,PLAN_OWNERSHIP VARCHAR(100)
,OWNER_NAME VARCHAR(100)
);

CREATE TABLE payers
(
 Id VARCHAR(100)
,NAME VARCHAR(100)
,OWNERSHIP VARCHAR(100)
,ADDRESS VARCHAR(100)
,CITY VARCHAR(100)
,STATE_HEADQUARTERED VARCHAR(100)
,ZIP VARCHAR(100)
,PHONE VARCHAR(100)
,AMOUNT_COVERED float
,AMOUNT_UNCOVERED float
,REVENUE float
,COVERED_ENCOUNTERS int
,UNCOVERED_ENCOUNTERS int
,COVERED_MEDICATIONS int
,UNCOVERED_MEDICATIONS int
,COVERED_PROCEDURES int
,UNCOVERED_PROCEDURES int
,COVERED_IMMUNIZATIONS int
,UNCOVERED_IMMUNIZATIONS int
,UNIQUE_CUSTOMERS int
,QOLS_AVG float
,MEMBER_MONTHS int
);

CREATE TABLE procedures
(
 START timestamp
,STOP timestamp
,PATIENT varchar(100)
,ENCOUNTER varchar(100)
,CODE bigint
,DESCRIPTION varchar(500)
,BASE_COST float
,REASONCODE varchar(30)
,REASONDESCRIPTION varchar(100)
);

CREATE TABLE providers
(
 Id varchar(100)
,ORGANIZATION varchar(100)
,NAME varchar(100)
,GENDER varchar(2)
,SPECIALITY varchar(100)
,ADDRESS varchar(100)
,CITY  varchar(80)
,STATE varchar(3)
,ZIP int
,LAT float
,LON float 
,ENCOUNTERS int
,PROCEDURES int
);

CREATE TABLE supplies
(
 DATE date
,PATIENT varchar(100) 
,ENCOUNTER varchar(100)
,CODE varchar(100)
,DESCRIPTION varchar(100) 
,QUANTITY int
);
